ALTER TABLE "Team" ADD COLUMN "leaderLabel" TEXT NOT NULL DEFAULT 'Coach';
ALTER TABLE "Team" ADD COLUMN "reserveCount" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Team" ADD COLUMN "reserveLabel" TEXT NOT NULL DEFAULT 'Reserv';
ALTER TABLE "Team" ADD COLUMN "reserve2Label" TEXT NOT NULL DEFAULT '10:a';
